In [1]:
import numpy as np

2. Create a null vector of size 10
hint: np.zeros

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

??????????

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

In [5]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
a.shape

(10,)

In [9]:
a_2 = np.array([0,0,0,0,1,0,0,0,0,0])
a_2 

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [10]:
a_2.shape

(10,)

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

In [13]:
a_3 = np.arange(10,50)
a_3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

In [15]:
a_5 = np.arange(0,9).reshape(3,3)
a_5 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

?????????

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

In [22]:
a_6 = np.array([1,2,0,0,4,0])
a_6

array([1, 2, 0, 0, 4, 0])

In [19]:
help(np.nonzero)

Help on _ArrayFunctionDispatcher in module numpy:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order.
    
    To group the indices by element, rather than dimension, use `argwhere`,
    which returns a row for each non-zero element.
    
    .. note::
    
       When called on a zero-d array or scalar, ``nonzero(a)`` is treated
       as ``nonzero(atleast_1d(a))``.
    
       .. deprecated:: 1.17.0
    
          Use `atleast_1d` explicitly if this behavior is deliberate.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the fl

In [25]:
a_6.nonzero() 

# ???

(array([0, 1, 4]),)

In [26]:
a_6[np.nonzero(a_6)]

array([1, 2, 4])

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

In [28]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

In [30]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)hint: min, max

In [42]:
np.random.seed(14)
a_9 = np.random.random((10,10))
a_9

array([[0.51394334, 0.77316505, 0.87042769, 0.00804695, 0.30973593,
        0.95760374, 0.51311671, 0.31828442, 0.53919994, 0.22125494],
       [0.80648136, 0.34225463, 0.53888885, 0.00587379, 0.67315248,
        0.21002426, 0.93255759, 0.37424475, 0.75241892, 0.763139  ],
       [0.87049946, 0.11011118, 0.30009198, 0.47490577, 0.67293672,
        0.25759243, 0.70115132, 0.65700006, 0.18200776, 0.32206299],
       [0.88753746, 0.08334916, 0.74656412, 0.06235005, 0.73148113,
        0.74251135, 0.40791581, 0.991383  , 0.4521373 , 0.18987854],
       [0.35162647, 0.71481167, 0.35743536, 0.05161855, 0.315919  ,
        0.99880461, 0.28790486, 0.46179587, 0.73526811, 0.94367895],
       [0.17540264, 0.21242138, 0.13247761, 0.20868119, 0.99568794,
        0.24664583, 0.11005316, 0.50232024, 0.45612182, 0.73449023],
       [0.62094354, 0.62107023, 0.15017263, 0.53827455, 0.12034724,
        0.15302552, 0.45017856, 0.42907235, 0.73366208, 0.07357155],
       [0.27878583, 0.16529377, 0.5080881

In [43]:
a_9.min()

0.00587378555105833

In [44]:
a_9.max()

0.9988046115649809

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

In [47]:
np.random.seed(14)
a_10 = np.random.random(30)
a_10

array([0.51394334, 0.77316505, 0.87042769, 0.00804695, 0.30973593,
       0.95760374, 0.51311671, 0.31828442, 0.53919994, 0.22125494,
       0.80648136, 0.34225463, 0.53888885, 0.00587379, 0.67315248,
       0.21002426, 0.93255759, 0.37424475, 0.75241892, 0.763139  ,
       0.87049946, 0.11011118, 0.30009198, 0.47490577, 0.67293672,
       0.25759243, 0.70115132, 0.65700006, 0.18200776, 0.32206299])

In [46]:
a_10.shape

(30,)

In [48]:
a_10.mean()

0.49907246661262505

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

In [49]:
help(np.diag)

Help on _ArrayFunctionDispatcher in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flatt

In [61]:
a_11 = np.zeros((5,5))
a_11

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
x = np.array([1, 2, 3, 4])

In [65]:
np.diag(x, k=-1)    # no se necesita llamar a la matriz anterior?

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

In [66]:
np.random.seed(14)
a_12 = np.random.random((5,5))
a_12

array([[0.51394334, 0.77316505, 0.87042769, 0.00804695, 0.30973593],
       [0.95760374, 0.51311671, 0.31828442, 0.53919994, 0.22125494],
       [0.80648136, 0.34225463, 0.53888885, 0.00587379, 0.67315248],
       [0.21002426, 0.93255759, 0.37424475, 0.75241892, 0.763139  ],
       [0.87049946, 0.11011118, 0.30009198, 0.47490577, 0.67293672]])

In [67]:
mean = np.mean(a_12)
std = np.std(a_12)

In [68]:
mean

0.5140943774327356

In [69]:
std

0.2815192832738289

In [70]:
a_12_standarized = (a_12 - mean) / std

In [71]:
a_12_standarized

array([[-5.36494901e-04,  9.20259073e-01,  1.26575098e+00,
        -1.79755867e+00, -7.25912803e-01],
       [ 1.57541379e+00, -3.47281775e-03, -6.95547212e-01,
         8.91788289e-02, -1.04021093e+00],
       [ 1.03860374e+00, -6.10401354e-01,  8.80737950e-02,
        -1.80527808e+00,  5.64998955e-01],
       [-1.08010404e+00,  1.48644601e+00, -4.96767491e-01,
         8.46565613e-01,  8.84644993e-01],
       [ 1.26600592e+00, -1.43501075e+00, -7.60169586e-01,
        -1.39204004e-01,  5.64232545e-01]])

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

In [72]:
help(np.intersect1d)

Help on _ArrayFunctionDispatcher in module numpy:

intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
    Find the intersection of two arrays.
    
    Return the sorted, unique values that are in both of the input arrays.
    
    Parameters
    ----------
    ar1, ar2 : array_like
        Input arrays. Will be flattened if not already 1D.
    assume_unique : bool
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  If True but ``ar1`` or ``ar2`` are not
        unique, incorrect results and out-of-bounds indices could result.
        Default is False.
    return_indices : bool
        If True, the indices which correspond to the intersection of the two
        arrays are returned. The first instance of a value is used if there are
        multiple. Default is False.
    
        .. versionadded:: 1.15.0
    
    Returns
    -------
    intersect1d : ndarray
        Sorted 1D array of common and unique elements.
  

In [73]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

In [75]:
np.random.seed(14)
a_14 = np.random.random(10)
a_14

array([0.51394334, 0.77316505, 0.87042769, 0.00804695, 0.30973593,
       0.95760374, 0.51311671, 0.31828442, 0.53919994, 0.22125494])

In [86]:
np.sort(a_14) #By default ascendente

array([0.00804695, 0.22125494, 0.30973593, 0.31828442, 0.51311671,
       0.51394334, 0.53919994, 0.77316505, 0.87042769, 0.95760374])

In [79]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second,

In [87]:
np.sort(a_14)[::-1] #Para hacerlo descendente:

array([0.95760374, 0.87042769, 0.77316505, 0.53919994, 0.51394334,
       0.51311671, 0.31828442, 0.30973593, 0.22125494, 0.00804695])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

In [89]:
np.random.seed(16)
a_15 = np.random.random(10)
a_15

array([0.22329108, 0.52316334, 0.55070146, 0.04560195, 0.36072884,
       0.22308094, 0.68872616, 0.16373143, 0.07032487, 0.94101086])

In [90]:
help(np.argmax)

Help on _ArrayFunctionDispatcher in module numpy:

argmax(a, axis=None, out=None, *, keepdims=<no value>)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the array.
    
        .. versionadded:: 1.22.0
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed. If `keepdims` is set to T

In [92]:
np.argmax(a_15)

9

In [93]:
a_15[np.argmax(a_15)] = 0

In [94]:
a_15

array([0.22329108, 0.52316334, 0.55070146, 0.04560195, 0.36072884,
       0.22308094, 0.68872616, 0.16373143, 0.07032487, 0.        ])

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

In [96]:
np.random.seed(42)
a_16 = np.random.random((3,3))
a_16

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [97]:
a_16.mean(axis = 1)

array([0.68574946, 0.30355721, 0.50845826])

In [98]:
np.mean(a_16, axis=1)

array([0.68574946, 0.30355721, 0.50845826])

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [107]:
Z = np.arange(10000)

In [108]:
np.random.shuffle(Z)

In [109]:
help(np.argsort)

Help on _ArrayFunctionDispatcher in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           T

In [110]:
help(np.argpartition)

Help on _ArrayFunctionDispatcher in module numpy:

argpartition(a, kth, axis=-1, kind='introselect', order=None)
    Perform an indirect partition along the given axis using the
    algorithm specified by the `kind` keyword. It returns an array of
    indices of the same shape as `a` that index data along the given
    axis in partitioned order.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    kth : int or sequence of ints
        Element index to partition by. The k-th element will be in its
        final sorted position and all smaller elements will be moved
        before it and all larger elements behind it. The order of all
        elements in the partitions is undefined. If provided with a
        sequence of k-th it will partition all of them into their sorted
        position at once.
    
        .. deprecated:: 1.22.0
            Passing booleans as index is deprecated.
    axis : int or None, optional
        A

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [113]:
np.random.seed(18)
a_18 = np.random.random((5,3))
a_18

array([[0.65037424, 0.50545337, 0.87860147],
       [0.18184023, 0.85223307, 0.75013629],
       [0.66610167, 0.98789545, 0.25696842],
       [0.02830593, 0.63571912, 0.84731239],
       [0.73617463, 0.02080711, 0.11160313]])

In [114]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called

In [130]:
np.random.seed(18)
matrix = np.random.randint(1, 20, size=(5, 3))
matrix

array([[11,  6, 18],
       [15, 19,  3],
       [ 9,  3, 18],
       [ 6, 16, 11],
       [11, 12,  5]])

In [132]:
np.where(matrix < 5, matrix, matrix**2)

array([[121,  36, 324],
       [225, 361,   3],
       [ 81,   3, 324],
       [ 36, 256, 121],
       [121, 144,  25]])

In [131]:
matriz_aleatoria = np.random.rand(5, 3) * 100
matriz_aleatoria 

array([[59.43226965, 28.86125901, 63.55478339],
       [20.35520128, 28.53591059, 62.21417203],
       [39.23830141, 55.50533734, 90.57299372],
       [52.09891184, 93.87479932, 73.71548503],
       [26.47179212, 42.45563483, 97.08884408]])

In [122]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called